my_project/colaborators/urls.py
from django.urls import path
from . import views

app_name = 'colaborators'

urlpatterns = [
    path('', views.show_colaborators, name="show_colaborators"),
    path('colaborators/', views.show_colaborators, name="show_colaborators"),
    path('new/', views.register_colaborator, name="register_colaborator"),
    path('new/post', views.register_colaborator, name="register_colaborator"),
    path('edit/<int:pk>', views.edit_colaborator, name="edit_colaborator"),
    path('delete/<int:pk>', views.delete_colaborator, name="delete_colaborator"),
]

my_project/members/urls.py
from django.urls import path
from . import views

app_name = "clients"

urlpatterns = [
    path('', views.list_client, name="list_client"),
    path('clients/', views.list_client, name="list_client"),
    path('new/', views.register_client, name="register_client"),
    path('new/post', views.register_client, name="register_client"),
    path('edit/<int:pk>', views.edit_client, name="edit_client"),
    path('delete/<int:pk>', views.delete_client, name="delete_client"),
    # path('delete/<int:pk>', views.delete_client, name="delete_client"),
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('members.urls'), name="clients"),
    path('colaborators/', include('colaborators.urls'), name="colaborators"),
    path('products/', include('products.urls'), name="products"),
    path('', lambda request: redirect('clients:list_client'), name="home"),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.show_products, name="show_products"),
    path('products/', views.show_products, name="show_products"),
    path('new/', views.register_product, name="register_product"),
    path('new/post', views.show_products, name="show_products"),
    path('edit/<int:pk>', views.edit_product, name="edit_product"),
    path('delete/<int:pk>', views.delete_product, name="delete_product"),
    # path('delete/<int:pk>', views.delete_client, name="delete_client"),
]

my_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SYSTEM OF COLABORATORS</title>
    <!-- BOOTSTRAP: -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
    crossorigin="anonymous">
     <!-- ICONS BOOTSTRAP --> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    
    <!-- MY CSS -->
    <link rel="stylesheet" href="{% static 'style/base.css' %}"> 
</head>
<body>
    <header class="fixed-top" >
        <nav class="navbar navbar-expand-lg px-5 shadow-sm" style="min-height: 70px;">
            <div>
                <i class="bi bi-list fs-3"></i>
            </div>
            <div class="navbar-nav w-75 px-5">
                <h1 style="display: flex; align-items: center;">
                    <a href="#" class="text-decoration-none text-black">
                        List Of Colaborators
                    </a>
                  
                </h1>
            </div>  
            <div class="collapse navbar-collapse border-start border-dark-subtle px-3">
                <ul class="navbar-nav">
                    <!-- style="margin-left: auto !important;" -->
                    <li class="nav-item li_nav mx-2 ">
                            <a class="nav-link fs-5 px-3 rounded-circle" href="#" ><i class="bi bi-bell-fill"></i></a>
                        <!-- <a class="nav-link" href="{% url 'clients:list_client' %}"><i class="bi bi-gear-fill"></i></a> -->
                    </li>
                    <li class="nav-item li_nav mx-2">
                        <a class="nav-link fs-5 px-3 rounded-circle" href="#"><i class="bi bi-gear-fill"></i></a>
                        <!-- <a class="nav-link" href="{% url 'colaborators:show_colaborators' %}">Colaborators</a> -->
                    </li>
                    <li class="nav-item li_nav mx-2">
                        <a class="nav-link fs-5 px-3 rounded-circle" href="#"><i class="bi bi-chat-fill"></i></a>
                        <!-- <a class="nav-link" href="{% url 'products:show_products' %}">Products</a> -->
                    </li>
                    <li class="nav-item li_nav mx-2 rounded-1 dropdown">
                        <button type="button"  class="btn btn-secondary dropdown-toggle text-black w-100 h-100"  
                                style="background-color: rgba(0,0,0,.1) !important; border: 0px;"  data-bs-toggle="dropdown" aria-expanded="false">
                                Valdemir
                        </button>
                        <!-- <i class="bi bi-caret-down-fill fs-6 mx-2"></i> -->
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Perfil</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Log out</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main id="base_principal"  >
        <div class="container mt-4 ">
            {% block content %}{% endblock %}
        </div>
    </main>
    
    <!-- <footer class="page-footer text-white text-center">
        <div class="row">
            <div class="col-md-6 py-3 d-flex align-items-center flex-column ">
                <h5 class="text-uppercase">Footer Content</h5>
                <p class="fs-6">Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis perferendis debitis excepturi.</p>
            </div>
            <hr class="clearfix w-100 d-md-none pb-3">
            <div class="col-md-3 mb-md-0 mb-3">
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled">
                <li>
                    <a href="#!" class="text-white-50 text-decoration-none" id="link_1">Link 1</a>
                </li>
                <li>
                    <a href="#!" class="text-white-50 text-decoration-none">Link 2</a>
                </li>
                <li>
                    <a href="#!" class="text-white-50 text-decoration-none">Link 3</a>
                </li>
                <li>
                    <a href="#!" class="text-white-50 text-decoration-none ">Link 4</a>
                </li>
                </ul>
            </div>
            <div class="col-md-3 mb-md-0 mb-3">
                <h5 class="text-uppercase">Links</h5>
                <ul class="list-unstyled" >
                <li>
                    <a href="#!" class="text-white-50 text-decoration-none" >Link 1</a>
                </li>
                <li>
                    <a href="#!" class="text-white-50 text-decoration-none">Link 2</a>
                </li>
                <li>
                    <a href="#!" class="text-white-50 text-decoration-none">Link 3</a>
                </li>
                <li>
                    <a href="#!" class="text-white-50 text-decoration-none">Link 4</a>
                </li>
                </ul>
            </div>
        </div>
        <p class="text-center pt-5">
            © 2024 PROJECT CRUD WITH DJANGO - DTA BOSCH. All rights reserved.
        </p>
      </footer> -->

    <script src="{% static 'dinamic/base.js' %}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>




  <!-- <div id="dropdown">
                <div class="dropdown navbar-toggler" >
                    <button id="menu_hamburguer" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {% comment %} <i class="bi bi-list"></i> {% endcomment %}
                        <i class="navbar-toggler-icon"></i>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="nav-link dropdown-item" href="#">Home</a></li>
                        <li><a class="nav-link" href="{% url 'clients:list_client' %}">Clients</a></li>
                        <li><a class="nav-link" href="{% url 'colaborators:show_colaborators' %}">Colaborators</a></li>
                    </ul>
                </div>
            </div> -->