my_project/members/urls.py
from django.urls import path
from . import views

app_name = "clients"

urlpatterns = [
    path('', views.list_client, name="list_client"),
    path('clients/', views.list_client, name="list_client"),
    path('new/', views.register_client, name="register_client"),
    path('new/post', views.register_client, name="register_client"),
    path('edit/<int:pk>', views.edit_client, name="edit_client"),
    path('delete/<int:pk>', views.delete_client, name="delete_client"),
    # path('delete/<int:pk>', views.delete_client, name="delete_client"),
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('members.urls'), name="clients"),
    path('colaborators/', include('colaborators.urls'), name="colaborators"),
    path('products/', include('products.urls'), name="products"),
    path('', lambda request: redirect('clients:list_client'), name="home"),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/members/models.py
from django.db import models

class Client(models.Model):
    name = models.CharField(max_length=100)
    address = models.TextField()
    cpf = models.CharField(max_length=14)
    date_birth = models.DateField()

    def __str__(self):
        return self.name
    



# Create your models here.

my_project/members/forms.py
from django import forms 
from .models import Client

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'address', 'cpf', 'date_birth'] 

my_project/members/views.py
# from django.shortcuts import render
# from django.http import HttpResponse

from django.shortcuts import render, redirect, get_object_or_404
from .models import Client
from .forms import ClientForm

# def members(request):
#     return HttpResponse("Hello world!")
# Create your views here.

def list_client(request):
    clients = Client.objects.all()
    return render(request, 'clients/list_client.html', {'clients':clients})

def register_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clients:list_client')
    else:
        form = ClientForm()
    return render(request, 'clients/register_client.html', {'form': form})
        
def edit_client(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            return redirect("clients:list_client")
    else:
        form = ClientForm(instance=client)
    return render(request, 'clients/edit_client.html', {'form': form})

def delete_client(request, pk):
    client = get_object_or_404(Client, pk=pk)
    client.delete()
    return redirect('clients:list_client')

my_project/members/templates/clients/delete_client.html
{% extends "base.html" %}
{% block content %}
<div class="base.html" >
    <h1>Confirm Exclusion</h1>
    <p>Confirm Do you have certain that wat to exclude the client "{{client.name}}"</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, exclude</button>
        <a href="{% url 'clients:list_client' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

my_project/members/templates/clients/edit_client.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Edit client</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}  
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'clients:list_client' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

my_project/members/templates/clients/list_client.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>List of clients</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Address</th>
                <th>CPF</th>
                <th>Date of Birth</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.name }}</td>
                <td>{{ client.address }}</td>
                <td>{{ client.cpf }}</td>
                <td>{{ client.date_birth }}</td>
                <td>
                    <a href="{% url 'clients:edit_client' client.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'clients:delete_client' client.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'clients:register_client' %}" class="btn btn-success">New Client</a>
</div>
{% endblock %}

my_project/members/templates/clients/make_client.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Make New Client</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }} 
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'clients:list_client' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

my_project/members/templates/clients/register_client.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Make New Client</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }} 
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'clients:list_client' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}