my_project/colaborators/urls.py
from django.urls import path
from . import views

app_name = 'colaborators'

urlpatterns = [
    path('', views.show_colaborators, name="show_colaborators"),
    path('colaborators/', views.show_colaborators, name="show_colaborators"),
    path('new/', views.register_colaborator, name="register_colaborator"),
    path('new/post', views.register_colaborator, name="register_colaborator"),
    path('edit/<int:pk>', views.edit_colaborator, name="edit_colaborator"),
    path('delete/<int:pk>', views.delete_colaborator, name="delete_colaborator"),
]

my_project/members/urls.py
from django.urls import path
from . import views

app_name = "clients"

urlpatterns = [
    path('', views.list_client, name="list_client"),
    path('clients/', views.list_client, name="list_client"),
    path('new/', views.register_client, name="register_client"),
    path('new/post', views.register_client, name="register_client"),
    path('edit/<int:pk>', views.edit_client, name="edit_client"),
    path('delete/<int:pk>', views.delete_client, name="delete_client"),
    # path('delete/<int:pk>', views.delete_client, name="delete_client"),
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('members.urls'), name="clients"),
    path('colaborators/', include('colaborators.urls'), name="colaborators"),
    path('products/', include('products.urls'), name="products"),
    path('', lambda request: redirect('clients:list_client'), name="home"),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.show_products, name="show_products"),
    path('products/', views.show_products, name="show_products"),
    path('new/', views.register_product, name="register_product"),
    path('new/post', views.show_products, name="show_products"),
    path('edit/<int:pk>', views.edit_product, name="edit_product"),
    path('delete/<int:pk>', views.delete_product, name="delete_product"),
    # path('delete/<int:pk>', views.delete_client, name="delete_client"),
]

my_project/colaborators/models.py
from django.db import models

class Colaborator(models.Model):
    EDV = models.IntegerField(unique=True)
    full_name = models.CharField(max_length=100)
    responsibillity = models.CharField(max_length=100)
    sector = models.CharField(max_length=100)
    address = models.TextField()
    date_admission = models.DateField()
    schedule_start = models.TimeField()
    schedule_end = models.TimeField()
    perfil_image = models.CharField(max_length=100)

    def __str__(self):
        return self.name

my_project/products/models.py
from django.db import models
# from django import forms 

class Products(models.Model):
    
    VOLTAGE_CHOICES = (
        (110,'110V'),
        (220,'220V')
    )

    MARK_CHOICES = (
        ('Microsoft','Microsoft'),
        ('Apple','Apple'),
        ('Bosch','Bosch'),
        ('Samsumg','Samsumg'),
        ('Xiaomi','Xiaomi')
    )

    TYPE_CHOICES = (
        ('Portable','Portable'),
        ('Static','Static')
    )

    description = models.TextField()
    price = models.DecimalField(max_digits = 5, decimal_places = 2)
    amount = models.IntegerField()
    weight = models.DecimalField(max_digits = 5 , decimal_places = 2)
    volts = models.IntegerField( choices = VOLTAGE_CHOICES )
    voltage = models.CharField( choices = MARK_CHOICES, max_length = 10)
    type = models.CharField( choices = TYPE_CHOICES, max_length = 10 )


    def __str__(self):
        return self.name

# Create your models here.

my_project/products/forms.py
from django import forms
from .models import Products

class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = ['description', 'price', 'amount', 'weight', 'volts', 'voltage', 'type']
        

my_project/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Products
from .forms import ProductForm
from PIL import Image
import copy
import os
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt


def show_products(request):
    products = Products.objects.all()
    return render(request, 'products/show_products.html', {'products': products})

@csrf_exempt
def register_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        
        # print(request.POST)
        if form.is_valid():
            # print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")    
            form.save()
            return redirect('products:show_products')
    else:
        form = ProductForm()
    return render(request, 'products/register_product.html', {'form': form})


def edit_product(request, pk):
    cliente = get_object_or_404(Products, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('products:show_products')
    else:
        form = ProductForm(instance=cliente)
    return render(request, 'products/edit_product.html', {'form': form})

def delete_product(request, pk):
    cliente = get_object_or_404(Products, pk=pk)
    cliente.delete()
    return redirect('products:show_products')


# Create your views here.

my_project/products/templates/products/delete_product.html
{% extends "base.html" %}
{% block content %}
<div class="base.html" >
    <h1>Confirm Exclusion</h1>
    <p>Confirm Do you have certain that wat to exclude the client "{{client.name}}"</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, exclude</button>
        <a href="{% url 'products:show_products' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

my_project/products/templates/products/edit_product.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Edit client</h1>
    <form method="post">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        <div class="row py-4">
            <div class="col">
                <div class="form-group">
                    <label for="id_nome_completo">Full Name:</label>
                    <input type="text" class="form-control" id="id_nome_completo" name="nome_completo" placeholder="Nome Completo" style="width: 600px;" required>
                </div>
                <div class="form-group">
                    <label for="id_edv">EDV:</label>
                    <input type="text" class="form-control" id="id_edv" name="edv" placeholder="EDV" style="width: 600px;" required>
                </div>
                <div class="form-group">
                    <label for="id_cargo">Cargo:</label>
                    <input type="text" class="form-control" id="id_cargo" name="cargo" placeholder="Cargo" style="width: 600px;" required>
                </div>
                <div class="form-group">
                    <label for="id_setor">Setor:</label>
                    <input type="text" class="form-control" id="id_setor" name="setor" placeholder="Setor" style="width: 600px;" required>
                </div>
                <div class="form-group">
                    <label for="id_endereco">Endereço:</label>
                    <input type="text" class="form-control" id="id_endereco" name="endereco" placeholder="Endereço" style="width: 600px;" required>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_horario_entrada">Horário de Entrada:</label>
                    <input type="text" class="form-control" id="id_horario_entrada" name="horario_entrada" placeholder="Horário de Entrada" style="width: 200px;" required>
                </div>
                <div class="form-group">
                    <label for="id_horario_saida">Horário de Saída:</label>
                    <input type="text" class="form-control" id="id_horario_saida" name="horario_saida" placeholder="Horário de Saída" style="width: 200px;" required>
                </div>
                <div class="form-group">
                    <label for="id_data_admissao">Data de Admissão:</label>
                    <input type="date" class="form-control" id="id_data_admissao" name="data_admissao" style="width: 200px;" required>
                </div>
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'colaborators:show_colaborators' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

my_project/products/templates/products/register_product.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Register a New Product</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }} 
        <button type="submit" class="btn btn-primary">Save</button>
        {% comment %} <a href="{% url 'clients:list_client' %}" class="btn btn-secondary">Cancel</a> {% endcomment %}
    </form>
</div>
    
{% comment %} <script>
    let perfil_photo_input = document.querySelector("#id_perfil_image")
    perfil_photo_input.addEventListener("change", (event) => {
        let image_visualization = document.querySelector('#image_visualization')
        let file = event.target.files[0]

        var reader = new FileReader();
        reader.onload = () => {
            var imageDataUrl = reader.result;
            console.log('URL de dados da imagem:', imageDataUrl);
            image_visualization.src = imageDataUrl
            image_visualization.style.display = 'block'
        };
        reader.readAsDataURL(file);
    })
</script> {% endcomment %}
{% endblock %}

my_project/products/templates/products/show_products.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>List of Products</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Description</th>
                <th>Price</th>
                <th>Amount</th>
                <th>Weight</th>
                <th>volts</th>
                <th>voltage</th>
                <th>type</th>
                
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.amount }}</td>
                <td>{{ product.weight }}</td>
                <td>{{ product.volts }}</td>
                <td>{{ product.voltage }}</td>
                <td>{{ product.type }}</td>
                <td>
                    <a href="{% url 'products:edit_product' product.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'products:delete_product' product.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'products:register_product' %}" class="btn btn-success">New Product</a>
</div>
{% endblock %}