my_project/colaborators/urls.py
from django.urls import path
from . import views

app_name = 'colaborators'

urlpatterns = [
    path('', views.show_colaborators, name="show_colaborators"),
    path('colaborators/', views.show_colaborators, name="show_colaborators"),
    path('new/', views.register_colaborator, name="register_colaborator"),
    path('new/post', views.register_colaborator, name="register_colaborator"),
    path('edit/<int:pk>', views.edit_colaborator, name="edit_colaborator"),
    path('delete/<int:pk>', views.delete_colaborator, name="delete_colaborator"),
]

my_project/members/urls.py
from django.urls import path
from . import views

app_name = "clients"

urlpatterns = [
    path('', views.list_client, name="list_client"),
    path('clients/', views.list_client, name="list_client"),
    path('new/', views.register_client, name="register_client"),
    path('new/post', views.register_client, name="register_client"),
    path('edit/<int:pk>', views.edit_client, name="edit_client"),
    path('delete/<int:pk>', views.delete_client, name="delete_client"),
    # path('delete/<int:pk>', views.delete_client, name="delete_client"),
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clients/', include('members.urls'), name="clients"),
    path('colaborators/', include('colaborators.urls'), name="colaborators"),
    path('products/', include('products.urls'), name="products"),
    path('', lambda request: redirect('clients:list_client'), name="home"),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/colaborators/models.py
from django.db import models

class Colaborator(models.Model):
    EDV = models.IntegerField(unique=True)
    full_name = models.CharField(max_length=100)
    responsibillity = models.CharField(max_length=100)
    sector = models.CharField(max_length=100)
    address = models.TextField()
    date_admission = models.DateField()
    schedule_start = models.TimeField()
    schedule_end = models.TimeField()
    perfil_image = models.CharField(max_length=100)

    def __str__(self):
        return self.name

my_project/colaborators/forms.py
from django import forms
from .models import Colaborator

class ColaboratorForm(forms.ModelForm):
    class Meta:
        model = Colaborator
        fields = ['EDV', 'full_name', 'responsibillity', 'sector', 'address', 'date_admission', 'schedule_start', 'schedule_end', 'perfil_image']
        

my_project/colaborators/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Colaborator
from .forms import ColaboratorForm
from PIL import Image
import copy
import os
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt


def show_colaborators(request):
    colaborators = Colaborator.objects.all()
    return render(request, 'colaborators/show_colaborators.html', {'colaborators': colaborators})

@csrf_exempt
def register_colaborator(request):
    if request.method == 'POST':
        
        file = request.FILES.get("perfil_image")
        img = Image.open(file)
        path = os.path.join(settings.BASE_DIR, f"media/{file.name}")
        file = request.FILES.get("perfil_image")
        img = Image.open(file)
        path = os.path.join(settings.BASE_DIR, f"media/{file.name}")
        
        post = copy.deepcopy(request.POST) 
        post["perfil_image"] = path
        form = ColaboratorForm(post)
        
        # print(request.POST)
        # if form.is_valid():
            # print("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
        img.save(path)    
        form.save()
        return redirect('colaborators:show_colaborators')
    else:
        form = ColaboratorForm()
    return render(request, 'colaborators/register_colaborator.html', {'form': form})


def edit_colaborator(request, pk):
    cliente = get_object_or_404(Colaborator, pk=pk)
    if request.method == 'POST':
        form = ColaboratorForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('colaborators:show_colaborators')
    else:
        form = ColaboratorForm(instance=cliente)
    return render(request, 'colaborators/edit_colaborator.html', {'form': form})

def delete_colaborator(request, pk):
    cliente = get_object_or_404(Colaborator, pk=pk)
    cliente.delete()
    return redirect('colaborators:show_colaborators')

my_project/colaborators/templates/colaborators/delete_colaborator.html
{% extends "base.html" %}
{% block content %}
<div class="base.html" >
    <h1>Confirm Exclusion</h1>
    <p>Confirm Do you have certain that wat to exclude the client "{{client.name}}"</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, exclude</button>
        <a href="{% url 'colaborators:show_colaborators' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

my_project/colaborators/templates/colaborators/edit_colaborator.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Edit client</h1>
    <form method="post">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} {% endcomment %}
        <div class="row py-4">
            <div class="col">
                <div class="form-group">
                    <label for="id_nome_completo">Full Name:</label>
                    <input type="text" class="form-control" id="id_nome_completo" name="nome_completo" placeholder="Nome Completo" style="width: 600px;" required>
                </div>
                <div class="form-group">
                    <label for="id_edv">EDV:</label>
                    <input type="text" class="form-control" id="id_edv" name="edv" placeholder="EDV" style="width: 600px;" required>
                </div>
                <div class="form-group">
                    <label for="id_cargo">Cargo:</label>
                    <input type="text" class="form-control" id="id_cargo" name="cargo" placeholder="Cargo" style="width: 600px;" required>
                </div>
                <div class="form-group">
                    <label for="id_setor">Setor:</label>
                    <input type="text" class="form-control" id="id_setor" name="setor" placeholder="Setor" style="width: 600px;" required>
                </div>
                <div class="form-group">
                    <label for="id_endereco">Endereço:</label>
                    <input type="text" class="form-control" id="id_endereco" name="endereco" placeholder="Endereço" style="width: 600px;" required>
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="id_horario_entrada">Horário de Entrada:</label>
                    <input type="text" class="form-control" id="id_horario_entrada" name="horario_entrada" placeholder="Horário de Entrada" style="width: 200px;" required>
                </div>
                <div class="form-group">
                    <label for="id_horario_saida">Horário de Saída:</label>
                    <input type="text" class="form-control" id="id_horario_saida" name="horario_saida" placeholder="Horário de Saída" style="width: 200px;" required>
                </div>
                <div class="form-group">
                    <label for="id_data_admissao">Data de Admissão:</label>
                    <input type="date" class="form-control" id="id_data_admissao" name="data_admissao" style="width: 200px;" required>
                </div>
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'colaborators:show_colaborators' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

my_project/colaborators/templates/colaborators/register_colaborator.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>Register a New Colaborator</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <input type="hidden" name="csrfmiddlewaretoken" value="OSISvdPWjtWCubSWNlPpPMtEBBOaUZtyvMJtQQ0b8s0TH7IE6KZUYfu0b2gHHFHR">        
        <div class="d-flex py-4">
            <div class="mx-5" style="width: 500px;">
                <div class="form-group">
                    <label for="id_full_name">Full Name:</label>
                    <input type="text" class="form-control" id="id_full_name" name="full_name" placeholder="Full Name" required>
                </div>
                <div class="form-group">
                    <label for="id_EDV">EDV:</label>
                    <input type="text" class="form-control" id="id_EDV" name="EDV" placeholder="EDV" required>
                </div>
                <div class="form-group">
                    <label for="id_responsibillity">Responsibillity:</label>
                    <input type="text" class="form-control" id="id_responsibillity" name="responsibillity" placeholder="Responsibillity" required>
                </div>
                <div class="form-group">
                    <label for="id_sector">Sector:</label>
                    <input type="text" class="form-control" id="id_sector" name="sector" placeholder="Sector" required>
                </div>
                <div class="form-group">
                    <label for="id_address">Address:</label>
                    <input type="text" class="form-control" id="id_address" name="address" placeholder="Address" required>
                </div>

                <!-- //////////////////////////////////////////////////////////////////////// -->
                <div class="form-group py-4 ">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="{% url 'colaborators:show_colaborators' %}" class="btn btn-secondary">Cancel</a>
                </div>
                <!-- //////////////////////////////////////////////////////////////////////// -->
            </div>
            
            <!-- //////////////////////////////////////////////////////////////////////// -->

            <div style="width: 200px;">
                <div class="form-group">
                    <label for="id_date_admission">Date of Admission:</label>
                    <input type="date" class="form-control" id="id_date_admission" name="date_admission" required>
                </div>
                <div class="form-group">
                    <label for="id_schedule_start">Schedule of Start:</label>
                    <input type="text" class="form-control" id="id_schedule_start" name="schedule_start" placeholder="Schedule of Start" required>
                </div>
                <div class="form-group">
                    <label for="id_schedule_end">Schedule of End:</label>
                    <input type="text" class="form-control" id="id_schedule_end" name="schedule_end" placeholder="Schedule of End" required>
                </div>
                <div class="form-group py-2">
                    <label for="id_perfil_image">Enter your perfil photo:</label>
                    <input type="file" class="form-control" id="id_perfil_image" name="perfil_image" required>
                </div>
                <div style="border: .1px solid rgba(0,0,0,.3); padding: 15px; width: 200px; border-radius: 10px; " >
                    <img src="#" alt="Perfil Image Visualization" id="image_visualization" style="display: none; object-fit:cover; margin: auto;" width="100px" height="100px">
                </div>
            </div>
        </div>
  
    </form>
</div>

<script>
    let perfil_photo_input = document.querySelector("#id_perfil_image")
    perfil_photo_input.addEventListener("change", (event) => {
        let image_visualization = document.querySelector('#image_visualization')
        let file = event.target.files[0]

        var reader = new FileReader();
        reader.onload = () => {
            var imageDataUrl = reader.result;
            console.log('URL de dados da imagem:', imageDataUrl);
            image_visualization.src = imageDataUrl
            image_visualization.style.display = 'block'
        };
        reader.readAsDataURL(file);
    })
</script>
{% endblock %}

my_project/colaborators/templates/colaborators/show_colaborators.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h1>List of colaborators</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>EDV</th>
                <th>Name</th>
                <th>Responsibillity</th>
                <th>Sector</th>
                <th>Address</th>
                <th>Date of admission</th>
                <th>Schedule of start</th>
                <th>Schedule of end</th>
            </tr>
        </thead>
        <tbody>
            {% for colaborator in colaborators %}
            <tr>
                <td>{{ colaborator.EDV }}</td>
                <td>{{ colaborator.full_name }}</td>
                <td>{{ colaborator.responsibillity }}</td>
                <td>{{ colaborator.sector }}</td>
                <td>{{ colaborator.address }}</td>
                <td>{{ colaborator.date_admission }}</td>
                <td>{{ colaborator.schedule_start }}</td>
                <td>{{ colaborator.schedule_end}}</td>
                <td>
                    <a href="{% url 'colaborators:edit_colaborator' colaborator.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'colaborators:delete_colaborator' colaborator.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'colaborators:register_colaborator' %}" class="btn btn-success">New Colaborator</a>
</div>
{% endblock %}